src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 * @ORM\HasLifecycleCallbacks
 *
 * @UniqueEntity("email")
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $deleted_at;

    /**
     * @ORM\OneToMany(targetEntity=Work::class, mappedBy="client")
     */
    private $works;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $business_id;

    /**
     * @ORM\OneToMany(targetEntity=Tariff::class, mappedBy="client", orphanRemoval=true)
     */
    private $tariffs;

    public function __construct()
    {
        $this->works = new ArrayCollection();
        $this->tariffs = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    /**
     * @ORM\PreUpdate
     */
    public function preUpdate()
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeImmutable $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * @return Collection|Work[]
     */
    public function getWorks(): Collection
    {
        return $this->works;
    }

    public function addWork(Work $work): self
    {
        if (!$this->works->contains($work)) {
            $this->works[] = $work;
            $work->setClient($this);
        }

        return $this;
    }

    public function removeWork(Work $work): self
    {
        if ($this->works->removeElement($work)) {
            // set the owning side to null (unless already changed)
            if ($work->getClient() === $this) {
                $work->setClient(null);
            }
        }

        return $this;
    }

    public function getBusinessId(): ?string
    {
        return $this->business_id;
    }

    public function setBusinessId(?string $business_id): self
    {
        $this->business_id = $business_id;

        return $this;
    }

    /**
     * @return Collection|Tariff[]
     */
    public function getTariffs(): Collection
    {
        return $this->tariffs;
    }

    public function addTariff(Tariff $tariff): self
    {
        if (!$this->tariffs->contains($tariff)) {
            $this->tariffs[] = $tariff;
            $tariff->setClientId($this);
        }

        return $this;
    }

    public function removeTariff(Tariff $tariff): self
    {
        if ($this->tariffs->removeElement($tariff)) {
            // set the owning side to null (unless already changed)
            if ($tariff->getClientId() === $this) {
                $tariff->setClientId(null);
            }
        }

        return $this;
    }
}

src/Entity/Work.php
<?php

namespace App\Entity;

use App\Repository\WorkRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=WorkRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Work
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="works")
     * @ORM\JoinColumn(nullable=false)
     *
     * @Assert\NotBlank
     */
    private $client;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank
     */
    private $subject;

    /**
     * @ORM\Column(type="float")
     *
     * @Assert\NotBlank
     * @Assert\Positive
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity=State::class, inversedBy="works")
     *
     * @Assert\NotBlank
     */
    private $state;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $deleted_at;

    /**
     * @ORM\OneToMany(targetEntity=Log::class, mappedBy="work")
     */
    private $logs;

    public function __construct()
    {
        $this->logs = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        $this->setCreatedAt(new \DateTimeImmutable());
    }

    /**
     * @ORM\PreUpdate
     */
    public function preUpdate()
    {
        $this->setUpdatedAt(new \DateTimeImmutable());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getState(): ?State
    {
        return $this->state;
    }

    public function setState(?State $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getDeletedAt(): ?\DateTimeImmutable
    {
        return $this->deleted_at;
    }

    public function setDeletedAt(?\DateTimeImmutable $deleted_at): self
    {
        $this->deleted_at = $deleted_at;

        return $this;
    }

    /**
     * @return Collection|Log[]
     */
    public function getLogs(): Collection
    {
        return $this->logs;
    }

    public function addLog(Log $log): self
    {
        if (!$this->logs->contains($log)) {
            $this->logs[] = $log;
            $log->setWork($this);
        }

        return $this;
    }

    public function removeLog(Log $log): self
    {
        if ($this->logs->removeElement($log)) {
            // set the owning side to null (unless already changed)
            if ($log->getWork() === $this) {
                $log->setWork(null);
            }
        }

        return $this;
    }
}

src/Form/WorkType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\State;
use App\Entity\Work;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;
use function Symfony\Component\String\u;

class WorkType extends AbstractType
{
    /**
     * @var TranslatorInterface
     */
    private $translator;

    /**
     * WorkType constructor.
     *
     * @param TranslatorInterface $translator
     */
    public function __construct(TranslatorInterface $translator)
    {
        $this->translator = $translator;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add("client", EntityType::class, [
                "label" => "work.form.client",
                "class" => Client::class,
                "choice_label" => "name",
                "query_builder" => function (EntityRepository $entityRepository) {
                    return $entityRepository->createQueryBuilder("client")
                        ->orderBy("client.name", "ASC");
                },
            ])
            ->add("subject", TextType::class, [
                "label" => "work.form.subject"
            ])
            ->add("price", NumberType::class, [
                "label" => "work.form.price"
            ])
            ->add("state", EntityType::class, [
                "label" => "work.form.state",
                "class" => State::class,
                "choice_label" => function ($state) {
                    return $this->translator->trans("state." . u($state->getName())->lower());
                },
                "choice_translation_domain" => false,
            ])
            ->add("submit", SubmitType::class, [
                "label" => "work.form.submit"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            "data_class" => Work::class,
        ]);
    }
}

src/Controller/WorkController.php
<?php

namespace App\Controller;

use App\Entity\Work;
use App\Form\WorkType;
use App\Repository\WorkRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class WorkController extends AbstractController
{
    /**
     * @Route("/works", name="work_list")
     *
     * @IsGranted("ROLE_USER")
     *
     * @param WorkRepository $workRepository
     * @param Request $request
     *
     * @return Response
     */
    public function list(WorkRepository $workRepository, Request $request): Response
    {
        $works = $workRepository->findAllOrdered($request->query->get("order", "work.id"), $request->query->get("dir", "asc"), $request->query->get("payed", false));

        return $this->render("work/list.html.twig", [
            "works" => $works
        ]);
    }

    /**
     * @Route("/work/add", name="work_add")
     *
     * @param Request $request
     *
     * @return Response
     */
    public function add(Request $request): Response
    {
        $form = $this->createForm(WorkType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $work = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($work);
            $entityManager->flush();

            return $this->redirectToRoute("work_list");
        }

        return $this->renderForm("work/add.html.twig", [
            "form" => $form,
        ]);
    }

    /**
     * @Route("/work/{id}/edit", name="work_edit")
     *
     * @param Work $work
     * @param Request $request
     *
     * @return Response
     */
    public function edit(Work $work, Request $request): Response
    {
        $form = $this->createForm(WorkType::class);
        $form->setData($work);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $work = $form->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            return $this->redirectToRoute("work_list");
        }

        return $this->renderForm("work/edit.html.twig", [
            "form" => $form,
        ]);
    }
}

templates/work/add.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ "work.add"|trans }}
{% endblock %}

{% block body %}
    {% include "_header.html.twig" %}

    <div class="container-fluid g-3" id="works">
        <h1 class="h3 mb-3">
            {{ "work.add"|trans }}
        </h1>

        <div class="row">
            <div class="col-4">
                <div class="card">
                    <div class="card-body pb-0">
                        {{ form(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/work/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ "work.add"|trans }}
{% endblock %}

{% block body %}
    {% include "_header.html.twig" %}

    <div class="container-fluid g-3" id="works">
        <h1 class="h3 mb-3">
            {{ "work.edit"|trans }}
        </h1>

        <div class="row">
            <div class="col-4">
                <div class="card">
                    <div class="card-body pb-0">
                        {{ form(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/work/layout.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ "work.list"|trans }}
{% endblock %}

{% block body %}
    {% include "_header.html.twig" %}

    <div class="container-fluid g-3" id="work">
        <h1 class="h3 mb-3">
            {% block heading %}{% endblock %}
        </h1>

        {% block content %}{% endblock %}
    </div>
{% endblock %}

templates/work/list.html.twig
{% extends "work/layout.html.twig" %}

{% block heading %}
    {{ "work.list"|trans }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-8 d-flex align-items-center justify-content-between">
            {% if is_granted("ROLE_SUPERADMIN") %}
                <a href="{{ path('work_add') }}" class="btn btn-primary">
                    {{ "work.add"|trans }}
                </a>
            {% endif %}

            <div>
                {% set payed = app.request.get("payed") ? null : 1 %}

                <a href="{{ path('work_list', {payed: payed}) }}" class="d-inline-flex align-items-center text-decoration-none {% if app.request.get("payed") %}text-success{% else %}text-danger{% endif %}">
                    <i class="bi bi-toggle-{{ app.request.get("payed") ? 'on' : 'off' }} fs-4"></i> <span class="text-dark ms-2">Zaplacené</span>
                </a>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-8 mb-3">
            <div class="card">
                <div class="card-body">
                    <table class="table mb-0">
                        <thead>
                            <tr>
                                {% set dir = app.request.get("dir") == "asc" ? "desc" : "asc" %}

                                <th>
                                    {% if app.request.query.get("order") != "client.name" %}
                                        {% set client_name_dir = "asc" %}
                                    {% else %}
                                        {% set client_name_dir = dir %}
                                    {% endif %}

                                    <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'order': 'client.name', 'dir': client_name_dir})|merge(app.request.query.all)) }}" class="link-dark">
                                        Klient

                                        {% if app.request.query.get("dir") and app.request.query.get("order") == "client.name" %}
                                            <i class="bi {% if app.request.query.get("dir") == "asc" %}bi-arrow-up{% else %}bi-arrow-down{% endif %}"></i>
                                        {% endif %}
                                    </a>
                                </th>

                                <th>
                                    Předmět
                                </th>

                                <th style="width: 125px;">
                                    {% if app.request.query.get("order") != "work.price" %}
                                        {% set work_price_dir = "asc" %}
                                    {% else %}
                                        {% set work_price_dir = dir %}
                                    {% endif %}

                                    <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'order': 'work.price', 'dir': work_price_dir})|merge(app.request.query.all)) }}" class="link-dark">
                                        Cena bez DPH

                                        {% if app.request.query.get("dir") and app.request.query.get("order") == "work.price" %}
                                            <i class="bi {% if app.request.query.get("dir") == "asc" %}bi-arrow-up{% else %}bi-arrow-down{% endif %}"></i>
                                        {% endif %}
                                    </a>
                                </th>

                                <th style="width: 140px;">
                                    {% if app.request.query.get("order") != "state.id" %}
                                        {% set state_id_dir = "asc" %}
                                    {% else %}
                                        {% set state_id_dir = dir %}
                                    {% endif %}

                                    <a href="{{ path(app.request.get('_route'), app.request.get('_route_params')|merge({'order': 'state.id', 'dir': state_id_dir})|merge(app.request.query.all)) }}" class="link-dark">
                                        Stav

                                        {% if app.request.query.get("dir") and app.request.query.get("order") == "state.id" %}
                                            <i class="bi {% if app.request.query.get("dir") == "asc" %}bi-arrow-up{% else %}bi-arrow-down{% endif %}"></i>
                                        {% endif %}
                                    </a>
                                </th>

                                <th style="width: 70px;">

                                </th>
                            </tr>
                        </thead>

                        <tbody>
                            {% set total = 0 %}

                            {% for work in works %}
                                <tr>
                                    <td id="client-name">
                                        <a role="button" tabindex="0" class="link-dark" data-bs-content="IČ: {{ work.client.businessId }}" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-trigger="focus">
                                            {{ work.client.name }}
                                        </a>
                                    </td>

                                    <td>
                                        {{ work.subject }}
                                    </td>

                                    <td>
                                        {% set total = total + work.price %}

                                        {{ work.price|format_currency("CZK", {fraction_digit: 0}) }}
                                    </td>

                                    <td>
                                        <span class="badge {% if work.state.id < 4 %}bg-dark{% else %}{{ work.state.id == 4 ? 'bg-danger' : (work.state.id == 5 ? 'bg-warning' : (work.state.id == 6 ? 'bg-success' : 'bg-info')) }}{% endif %}">
                                            {{ ["state.", work.state.name]|join|lower|trans }}
                                        </span>

                                        {% if work.logs.count %}
                                            {% if (date(work.logs.last.createdAt) <= date("-2 weeks") and work.state.id < 5) or (date(work.logs.last.createdAt) <= date("-1 month") and work.state.id >= 5) %}
                                                <i class="bi bi-exclamation-circle text-danger ms-1"></i>
                                            {% endif %}
                                        {% endif %}
                                    </td>

                                    <td class="text-end">
                                        <a href="{{ path('work_edit', {id: work.id}) }}" class="d-inline-flex">
                                            <i class="bi bi-pencil"></i>
                                        </a>

                                        <a href="{{ path('log_list', app.request.query.all|merge({id: work.id})) }}" class="d-inline-flex ms-2">
                                            <i class="bi bi-clipboard"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>

                        <tfoot>
                            <tr>
                                <th class="border-0" colspan="2">
                                    Celkem
                                </th>

                                <th class="border-0">
                                    {{ total|format_currency("CZK", {fraction_digit: 0}) }}
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-4 mb-3">
            <div class="sticky-top" style="top: 1rem;">
                {% block sidebar %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}